---
# GCP Admin service account secret - used by GCP ProviderConfig
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-gcp
type: Opaque
data:
  credentials.json: BASE64ENCODED_GCP_PROVIDER_CREDS
---
# GCP ProviderConfig with service account secret reference
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: example
spec:
  projectID: PROJECT_ID
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-gcp
      key: credentials.json
