/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha2

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SSLCertObservation struct {
	Cert *string `json:"cert,omitempty" tf:"cert,omitempty"`

	CertSerialNumber *string `json:"certSerialNumber,omitempty" tf:"cert_serial_number,omitempty"`

	CreateTime *string `json:"createTime,omitempty" tf:"create_time,omitempty"`

	ExpirationTime *string `json:"expirationTime,omitempty" tf:"expiration_time,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ServerCACert *string `json:"serverCaCert,omitempty" tf:"server_ca_cert,omitempty"`

	Sha1Fingerprint *string `json:"sha1Fingerprint,omitempty" tf:"sha1_fingerprint,omitempty"`
}

type SSLCertParameters struct {

	// The common name to be used in the certificate to identify the client. Constrained to [a-zA-Z.-_ ]+. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Required
	CommonName *string `json:"commonName" tf:"common_name,omitempty"`

	// The name of the Cloud SQL instance. Changing this forces a new resource to be created.
	// +crossplane:generate:reference:type=DatabaseInstance
	// +kubebuilder:validation:Optional
	Instance *string `json:"instance,omitempty" tf:"instance,omitempty"`

	// +kubebuilder:validation:Optional
	InstanceRef *v1.Reference `json:"instanceRef,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	InstanceSelector *v1.Selector `json:"instanceSelector,omitempty" tf:"-"`

	// The ID of the project in which the resource belongs. If it is not provided, the provider project is used.
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

// SSLCertSpec defines the desired state of SSLCert
type SSLCertSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SSLCertParameters `json:"forProvider"`
}

// SSLCertStatus defines the observed state of SSLCert.
type SSLCertStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SSLCertObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// SSLCert is the Schema for the SSLCerts API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcpjet}
type SSLCert struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SSLCertSpec   `json:"spec"`
	Status            SSLCertStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SSLCertList contains a list of SSLCerts
type SSLCertList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SSLCert `json:"items"`
}

// Repository type metadata.
var (
	SSLCert_Kind             = "SSLCert"
	SSLCert_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SSLCert_Kind}.String()
	SSLCert_KindAPIVersion   = SSLCert_Kind + "." + CRDGroupVersion.String()
	SSLCert_GroupVersionKind = CRDGroupVersion.WithKind(SSLCert_Kind)
)

func init() {
	SchemeBuilder.Register(&SSLCert{}, &SSLCertList{})
}
