---
apiVersion: compute.gcp.crossplane.io/v1alpha1
kind: Router
metadata:
  name: router-test
spec:
  forProvider:
    description: A test router to verify provider-gcp changes
    region: us-west1
    networkRef:
      name: network-example
    nats:
      - name: router-nat-1
        minPortsPerVm: 2
        natIpAllocateOption: AUTO_ONLY
        sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
  providerConfigRef:
    name: default