---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  name: demo-serviceaccount-key
spec:
  forProvider:
    serviceAccountRef:
      name: perfect-test-sa
  publishConnectionDetailsTo:
    name: demo-serviceaccount-key
    metadata:
      labels:
        environment: development
        team: backend
      annotations:
        argocd.argoproj.io/sync-options: Prune=false
      type: Opaque
    configRef:
      name: vault
