// +build !ignore_autogenerated

/*
Copyright 2019 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceleratorConfigClusterStatus) DeepCopyInto(out *AcceleratorConfigClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceleratorConfigClusterStatus.
func (in *AcceleratorConfigClusterStatus) DeepCopy() *AcceleratorConfigClusterStatus {
	if in == nil {
		return nil
	}
	out := new(AcceleratorConfigClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddonsConfig) DeepCopyInto(out *AddonsConfig) {
	*out = *in
	if in.CloudRunConfig != nil {
		in, out := &in.CloudRunConfig, &out.CloudRunConfig
		*out = new(CloudRunConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HorizontalPodAutoscaling != nil {
		in, out := &in.HorizontalPodAutoscaling, &out.HorizontalPodAutoscaling
		*out = new(HorizontalPodAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPLoadBalancing != nil {
		in, out := &in.HTTPLoadBalancing, &out.HTTPLoadBalancing
		*out = new(HTTPLoadBalancing)
		(*in).DeepCopyInto(*out)
	}
	if in.IstioConfig != nil {
		in, out := &in.IstioConfig, &out.IstioConfig
		*out = new(IstioConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesDashboard != nil {
		in, out := &in.KubernetesDashboard, &out.KubernetesDashboard
		*out = new(KubernetesDashboard)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicyConfig != nil {
		in, out := &in.NetworkPolicyConfig, &out.NetworkPolicyConfig
		*out = new(NetworkPolicyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddonsConfig.
func (in *AddonsConfig) DeepCopy() *AddonsConfig {
	if in == nil {
		return nil
	}
	out := new(AddonsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticatorGroupsConfig) DeepCopyInto(out *AuthenticatorGroupsConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SecurityGroup != nil {
		in, out := &in.SecurityGroup, &out.SecurityGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticatorGroupsConfig.
func (in *AuthenticatorGroupsConfig) DeepCopy() *AuthenticatorGroupsConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticatorGroupsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoUpgradeOptionsClusterStatus) DeepCopyInto(out *AutoUpgradeOptionsClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoUpgradeOptionsClusterStatus.
func (in *AutoUpgradeOptionsClusterStatus) DeepCopy() *AutoUpgradeOptionsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(AutoUpgradeOptionsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoprovisioningNodePoolDefaults) DeepCopyInto(out *AutoprovisioningNodePoolDefaults) {
	*out = *in
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoprovisioningNodePoolDefaults.
func (in *AutoprovisioningNodePoolDefaults) DeepCopy() *AutoprovisioningNodePoolDefaults {
	if in == nil {
		return nil
	}
	out := new(AutoprovisioningNodePoolDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryDestination) DeepCopyInto(out *BigQueryDestination) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryDestination.
func (in *BigQueryDestination) DeepCopy() *BigQueryDestination {
	if in == nil {
		return nil
	}
	out := new(BigQueryDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinaryAuthorization) DeepCopyInto(out *BinaryAuthorization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinaryAuthorization.
func (in *BinaryAuthorization) DeepCopy() *BinaryAuthorization {
	if in == nil {
		return nil
	}
	out := new(BinaryAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CidrBlock) DeepCopyInto(out *CidrBlock) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CidrBlock.
func (in *CidrBlock) DeepCopy() *CidrBlock {
	if in == nil {
		return nil
	}
	out := new(CidrBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientCertificateConfig) DeepCopyInto(out *ClientCertificateConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientCertificateConfig.
func (in *ClientCertificateConfig) DeepCopy() *ClientCertificateConfig {
	if in == nil {
		return nil
	}
	out := new(ClientCertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudRunConfig) DeepCopyInto(out *CloudRunConfig) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudRunConfig.
func (in *CloudRunConfig) DeepCopy() *CloudRunConfig {
	if in == nil {
		return nil
	}
	out := new(CloudRunConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAutoscaling) DeepCopyInto(out *ClusterAutoscaling) {
	*out = *in
	if in.AutoprovisioningLocations != nil {
		in, out := &in.AutoprovisioningLocations, &out.AutoprovisioningLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AutoprovisioningNodePoolDefaults != nil {
		in, out := &in.AutoprovisioningNodePoolDefaults, &out.AutoprovisioningNodePoolDefaults
		*out = new(AutoprovisioningNodePoolDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableNodeAutoprovisioning != nil {
		in, out := &in.EnableNodeAutoprovisioning, &out.EnableNodeAutoprovisioning
		*out = new(bool)
		**out = **in
	}
	if in.ResourceLimits != nil {
		in, out := &in.ResourceLimits, &out.ResourceLimits
		*out = make([]*ResourceLimit, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ResourceLimit)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAutoscaling.
func (in *ClusterAutoscaling) DeepCopy() *ClusterAutoscaling {
	if in == nil {
		return nil
	}
	out := new(ClusterAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumptionMeteringConfig) DeepCopyInto(out *ConsumptionMeteringConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumptionMeteringConfig.
func (in *ConsumptionMeteringConfig) DeepCopy() *ConsumptionMeteringConfig {
	if in == nil {
		return nil
	}
	out := new(ConsumptionMeteringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DailyMaintenanceWindowSpec) DeepCopyInto(out *DailyMaintenanceWindowSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DailyMaintenanceWindowSpec.
func (in *DailyMaintenanceWindowSpec) DeepCopy() *DailyMaintenanceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(DailyMaintenanceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DailyMaintenanceWindowStatus) DeepCopyInto(out *DailyMaintenanceWindowStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DailyMaintenanceWindowStatus.
func (in *DailyMaintenanceWindowStatus) DeepCopy() *DailyMaintenanceWindowStatus {
	if in == nil {
		return nil
	}
	out := new(DailyMaintenanceWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseEncryption) DeepCopyInto(out *DatabaseEncryption) {
	*out = *in
	if in.KeyName != nil {
		in, out := &in.KeyName, &out.KeyName
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseEncryption.
func (in *DatabaseEncryption) DeepCopy() *DatabaseEncryption {
	if in == nil {
		return nil
	}
	out := new(DatabaseEncryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKECluster) DeepCopyInto(out *GKECluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKECluster.
func (in *GKECluster) DeepCopy() *GKECluster {
	if in == nil {
		return nil
	}
	out := new(GKECluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKECluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterClass) DeepCopyInto(out *GKEClusterClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.SpecTemplate.DeepCopyInto(&out.SpecTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterClass.
func (in *GKEClusterClass) DeepCopy() *GKEClusterClass {
	if in == nil {
		return nil
	}
	out := new(GKEClusterClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKEClusterClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterClassList) DeepCopyInto(out *GKEClusterClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GKEClusterClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterClassList.
func (in *GKEClusterClassList) DeepCopy() *GKEClusterClassList {
	if in == nil {
		return nil
	}
	out := new(GKEClusterClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKEClusterClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterClassSpecTemplate) DeepCopyInto(out *GKEClusterClassSpecTemplate) {
	*out = *in
	in.ClassSpecTemplate.DeepCopyInto(&out.ClassSpecTemplate)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterClassSpecTemplate.
func (in *GKEClusterClassSpecTemplate) DeepCopy() *GKEClusterClassSpecTemplate {
	if in == nil {
		return nil
	}
	out := new(GKEClusterClassSpecTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterList) DeepCopyInto(out *GKEClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GKECluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterList.
func (in *GKEClusterList) DeepCopy() *GKEClusterList {
	if in == nil {
		return nil
	}
	out := new(GKEClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GKEClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterObservation) DeepCopyInto(out *GKEClusterObservation) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*StatusCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StatusCondition)
				**out = **in
			}
		}
	}
	if in.MaintenancePolicy != nil {
		in, out := &in.MaintenancePolicy, &out.MaintenancePolicy
		*out = new(MaintenancePolicyStatus)
		**out = **in
	}
	if in.NetworkConfig != nil {
		in, out := &in.NetworkConfig, &out.NetworkConfig
		*out = new(NetworkConfigStatus)
		**out = **in
	}
	if in.PrivateClusterConfig != nil {
		in, out := &in.PrivateClusterConfig, &out.PrivateClusterConfig
		*out = new(PrivateClusterConfigStatus)
		**out = **in
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]*NodePoolClusterStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NodePoolClusterStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterObservation.
func (in *GKEClusterObservation) DeepCopy() *GKEClusterObservation {
	if in == nil {
		return nil
	}
	out := new(GKEClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterParameters) DeepCopyInto(out *GKEClusterParameters) {
	*out = *in
	if in.AddonsConfig != nil {
		in, out := &in.AddonsConfig, &out.AddonsConfig
		*out = new(AddonsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticatorGroupsConfig != nil {
		in, out := &in.AuthenticatorGroupsConfig, &out.AuthenticatorGroupsConfig
		*out = new(AuthenticatorGroupsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(ClusterAutoscaling)
		(*in).DeepCopyInto(*out)
	}
	if in.BinaryAuthorization != nil {
		in, out := &in.BinaryAuthorization, &out.BinaryAuthorization
		*out = new(BinaryAuthorization)
		**out = **in
	}
	if in.ClusterIpv4Cidr != nil {
		in, out := &in.ClusterIpv4Cidr, &out.ClusterIpv4Cidr
		*out = new(string)
		**out = **in
	}
	if in.DatabaseEncryption != nil {
		in, out := &in.DatabaseEncryption, &out.DatabaseEncryption
		*out = new(DatabaseEncryption)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultMaxPodsConstraint != nil {
		in, out := &in.DefaultMaxPodsConstraint, &out.DefaultMaxPodsConstraint
		*out = new(MaxPodsConstraint)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableKubernetesAlpha != nil {
		in, out := &in.EnableKubernetesAlpha, &out.EnableKubernetesAlpha
		*out = new(bool)
		**out = **in
	}
	if in.EnableTpu != nil {
		in, out := &in.EnableTpu, &out.EnableTpu
		*out = new(bool)
		**out = **in
	}
	if in.InitialClusterVersion != nil {
		in, out := &in.InitialClusterVersion, &out.InitialClusterVersion
		*out = new(string)
		**out = **in
	}
	if in.IPAllocationPolicy != nil {
		in, out := &in.IPAllocationPolicy, &out.IPAllocationPolicy
		*out = new(IPAllocationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.LabelFingerprint != nil {
		in, out := &in.LabelFingerprint, &out.LabelFingerprint
		*out = new(string)
		**out = **in
	}
	if in.LegacyAbac != nil {
		in, out := &in.LegacyAbac, &out.LegacyAbac
		*out = new(LegacyAbac)
		**out = **in
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoggingService != nil {
		in, out := &in.LoggingService, &out.LoggingService
		*out = new(string)
		**out = **in
	}
	if in.MaintenancePolicy != nil {
		in, out := &in.MaintenancePolicy, &out.MaintenancePolicy
		*out = new(MaintenancePolicySpec)
		**out = **in
	}
	if in.MasterAuth != nil {
		in, out := &in.MasterAuth, &out.MasterAuth
		*out = new(MasterAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.MasterAuthorizedNetworksConfig != nil {
		in, out := &in.MasterAuthorizedNetworksConfig, &out.MasterAuthorizedNetworksConfig
		*out = new(MasterAuthorizedNetworksConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MonitoringService != nil {
		in, out := &in.MonitoringService, &out.MonitoringService
		*out = new(string)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
	if in.NetworkRef != nil {
		in, out := &in.NetworkRef, &out.NetworkRef
		*out = new(v1alpha1.Reference)
		**out = **in
	}
	if in.NetworkSelector != nil {
		in, out := &in.NetworkSelector, &out.NetworkSelector
		*out = new(v1alpha1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkConfig != nil {
		in, out := &in.NetworkConfig, &out.NetworkConfig
		*out = new(NetworkConfigSpec)
		**out = **in
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityPolicyConfig != nil {
		in, out := &in.PodSecurityPolicyConfig, &out.PodSecurityPolicyConfig
		*out = new(PodSecurityPolicyConfig)
		**out = **in
	}
	if in.PrivateClusterConfig != nil {
		in, out := &in.PrivateClusterConfig, &out.PrivateClusterConfig
		*out = new(PrivateClusterConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceLabels != nil {
		in, out := &in.ResourceLabels, &out.ResourceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceUsageExportConfig != nil {
		in, out := &in.ResourceUsageExportConfig, &out.ResourceUsageExportConfig
		*out = new(ResourceUsageExportConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Subnetwork != nil {
		in, out := &in.Subnetwork, &out.Subnetwork
		*out = new(string)
		**out = **in
	}
	if in.SubnetworkRef != nil {
		in, out := &in.SubnetworkRef, &out.SubnetworkRef
		*out = new(v1alpha1.Reference)
		**out = **in
	}
	if in.SubnetworkSelector != nil {
		in, out := &in.SubnetworkSelector, &out.SubnetworkSelector
		*out = new(v1alpha1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.TierSettings != nil {
		in, out := &in.TierSettings, &out.TierSettings
		*out = new(TierSettings)
		**out = **in
	}
	if in.VerticalPodAutoscaling != nil {
		in, out := &in.VerticalPodAutoscaling, &out.VerticalPodAutoscaling
		*out = new(VerticalPodAutoscaling)
		**out = **in
	}
	if in.WorkloadIdentityConfig != nil {
		in, out := &in.WorkloadIdentityConfig, &out.WorkloadIdentityConfig
		*out = new(WorkloadIdentityConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterParameters.
func (in *GKEClusterParameters) DeepCopy() *GKEClusterParameters {
	if in == nil {
		return nil
	}
	out := new(GKEClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterSpec) DeepCopyInto(out *GKEClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterSpec.
func (in *GKEClusterSpec) DeepCopy() *GKEClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GKEClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEClusterStatus) DeepCopyInto(out *GKEClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEClusterStatus.
func (in *GKEClusterStatus) DeepCopy() *GKEClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GKEClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancing) DeepCopyInto(out *HTTPLoadBalancing) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancing.
func (in *HTTPLoadBalancing) DeepCopy() *HTTPLoadBalancing {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorizontalPodAutoscaling) DeepCopyInto(out *HorizontalPodAutoscaling) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorizontalPodAutoscaling.
func (in *HorizontalPodAutoscaling) DeepCopy() *HorizontalPodAutoscaling {
	if in == nil {
		return nil
	}
	out := new(HorizontalPodAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPAllocationPolicy) DeepCopyInto(out *IPAllocationPolicy) {
	*out = *in
	if in.AllowRouteOverlap != nil {
		in, out := &in.AllowRouteOverlap, &out.AllowRouteOverlap
		*out = new(bool)
		**out = **in
	}
	if in.ClusterIpv4CidrBlock != nil {
		in, out := &in.ClusterIpv4CidrBlock, &out.ClusterIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.ClusterSecondaryRangeName != nil {
		in, out := &in.ClusterSecondaryRangeName, &out.ClusterSecondaryRangeName
		*out = new(string)
		**out = **in
	}
	if in.CreateSubnetwork != nil {
		in, out := &in.CreateSubnetwork, &out.CreateSubnetwork
		*out = new(bool)
		**out = **in
	}
	if in.NodeIpv4CidrBlock != nil {
		in, out := &in.NodeIpv4CidrBlock, &out.NodeIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.ServicesIpv4CidrBlock != nil {
		in, out := &in.ServicesIpv4CidrBlock, &out.ServicesIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.ServicesSecondaryRangeName != nil {
		in, out := &in.ServicesSecondaryRangeName, &out.ServicesSecondaryRangeName
		*out = new(string)
		**out = **in
	}
	if in.SubnetworkName != nil {
		in, out := &in.SubnetworkName, &out.SubnetworkName
		*out = new(string)
		**out = **in
	}
	if in.TpuIpv4CidrBlock != nil {
		in, out := &in.TpuIpv4CidrBlock, &out.TpuIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
	if in.UseIPAliases != nil {
		in, out := &in.UseIPAliases, &out.UseIPAliases
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPAllocationPolicy.
func (in *IPAllocationPolicy) DeepCopy() *IPAllocationPolicy {
	if in == nil {
		return nil
	}
	out := new(IPAllocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioConfig) DeepCopyInto(out *IstioConfig) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(string)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioConfig.
func (in *IstioConfig) DeepCopy() *IstioConfig {
	if in == nil {
		return nil
	}
	out := new(IstioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesDashboard) DeepCopyInto(out *KubernetesDashboard) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesDashboard.
func (in *KubernetesDashboard) DeepCopy() *KubernetesDashboard {
	if in == nil {
		return nil
	}
	out := new(KubernetesDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LegacyAbac) DeepCopyInto(out *LegacyAbac) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LegacyAbac.
func (in *LegacyAbac) DeepCopy() *LegacyAbac {
	if in == nil {
		return nil
	}
	out := new(LegacyAbac)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePolicySpec) DeepCopyInto(out *MaintenancePolicySpec) {
	*out = *in
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenancePolicySpec.
func (in *MaintenancePolicySpec) DeepCopy() *MaintenancePolicySpec {
	if in == nil {
		return nil
	}
	out := new(MaintenancePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenancePolicyStatus) DeepCopyInto(out *MaintenancePolicyStatus) {
	*out = *in
	out.Window = in.Window
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenancePolicyStatus.
func (in *MaintenancePolicyStatus) DeepCopy() *MaintenancePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenancePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowSpec) DeepCopyInto(out *MaintenanceWindowSpec) {
	*out = *in
	out.DailyMaintenanceWindow = in.DailyMaintenanceWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowSpec.
func (in *MaintenanceWindowSpec) DeepCopy() *MaintenanceWindowSpec {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindowStatus) DeepCopyInto(out *MaintenanceWindowStatus) {
	*out = *in
	out.DailyMaintenanceWindow = in.DailyMaintenanceWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindowStatus.
func (in *MaintenanceWindowStatus) DeepCopy() *MaintenanceWindowStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterAuth) DeepCopyInto(out *MasterAuth) {
	*out = *in
	if in.ClientCertificateConfig != nil {
		in, out := &in.ClientCertificateConfig, &out.ClientCertificateConfig
		*out = new(ClientCertificateConfig)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterAuth.
func (in *MasterAuth) DeepCopy() *MasterAuth {
	if in == nil {
		return nil
	}
	out := new(MasterAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterAuthorizedNetworksConfig) DeepCopyInto(out *MasterAuthorizedNetworksConfig) {
	*out = *in
	if in.CidrBlocks != nil {
		in, out := &in.CidrBlocks, &out.CidrBlocks
		*out = make([]*CidrBlock, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CidrBlock)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterAuthorizedNetworksConfig.
func (in *MasterAuthorizedNetworksConfig) DeepCopy() *MasterAuthorizedNetworksConfig {
	if in == nil {
		return nil
	}
	out := new(MasterAuthorizedNetworksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxPodsConstraint) DeepCopyInto(out *MaxPodsConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxPodsConstraint.
func (in *MaxPodsConstraint) DeepCopy() *MaxPodsConstraint {
	if in == nil {
		return nil
	}
	out := new(MaxPodsConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigSpec) DeepCopyInto(out *NetworkConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigSpec.
func (in *NetworkConfigSpec) DeepCopy() *NetworkConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigStatus) DeepCopyInto(out *NetworkConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigStatus.
func (in *NetworkConfigStatus) DeepCopy() *NetworkConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicy) DeepCopyInto(out *NetworkPolicy) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicy.
func (in *NetworkPolicy) DeepCopy() *NetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyConfig) DeepCopyInto(out *NetworkPolicyConfig) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyConfig.
func (in *NetworkPolicyConfig) DeepCopy() *NetworkPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfigClusterStatus) DeepCopyInto(out *NodeConfigClusterStatus) {
	*out = *in
	if in.Accelerators != nil {
		in, out := &in.Accelerators, &out.Accelerators
		*out = make([]*AcceleratorConfigClusterStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AcceleratorConfigClusterStatus)
				**out = **in
			}
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.OauthScopes != nil {
		in, out := &in.OauthScopes, &out.OauthScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SandboxConfig != nil {
		in, out := &in.SandboxConfig, &out.SandboxConfig
		*out = new(SandboxConfigClusterStatus)
		**out = **in
	}
	if in.ShieldedInstanceConfig != nil {
		in, out := &in.ShieldedInstanceConfig, &out.ShieldedInstanceConfig
		*out = new(ShieldedInstanceConfigClusterStatus)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]*NodeTaintClusterStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NodeTaintClusterStatus)
				**out = **in
			}
		}
	}
	if in.WorkloadMetadataConfig != nil {
		in, out := &in.WorkloadMetadataConfig, &out.WorkloadMetadataConfig
		*out = new(WorkloadMetadataConfigClusterStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfigClusterStatus.
func (in *NodeConfigClusterStatus) DeepCopy() *NodeConfigClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NodeConfigClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeManagementClusterStatus) DeepCopyInto(out *NodeManagementClusterStatus) {
	*out = *in
	if in.UpgradeOptions != nil {
		in, out := &in.UpgradeOptions, &out.UpgradeOptions
		*out = new(AutoUpgradeOptionsClusterStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeManagementClusterStatus.
func (in *NodeManagementClusterStatus) DeepCopy() *NodeManagementClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NodeManagementClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolAutoscalingClusterStatus) DeepCopyInto(out *NodePoolAutoscalingClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolAutoscalingClusterStatus.
func (in *NodePoolAutoscalingClusterStatus) DeepCopy() *NodePoolAutoscalingClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NodePoolAutoscalingClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolClusterStatus) DeepCopyInto(out *NodePoolClusterStatus) {
	*out = *in
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(NodePoolAutoscalingClusterStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*StatusCondition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StatusCondition)
				**out = **in
			}
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(NodeConfigClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceGroupUrls != nil {
		in, out := &in.InstanceGroupUrls, &out.InstanceGroupUrls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Management != nil {
		in, out := &in.Management, &out.Management
		*out = new(NodeManagementClusterStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxPodsConstraint != nil {
		in, out := &in.MaxPodsConstraint, &out.MaxPodsConstraint
		*out = new(MaxPodsConstraint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolClusterStatus.
func (in *NodePoolClusterStatus) DeepCopy() *NodePoolClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NodePoolClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTaintClusterStatus) DeepCopyInto(out *NodeTaintClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTaintClusterStatus.
func (in *NodeTaintClusterStatus) DeepCopy() *NodeTaintClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NodeTaintClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSecurityPolicyConfig) DeepCopyInto(out *PodSecurityPolicyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSecurityPolicyConfig.
func (in *PodSecurityPolicyConfig) DeepCopy() *PodSecurityPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(PodSecurityPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateClusterConfigSpec) DeepCopyInto(out *PrivateClusterConfigSpec) {
	*out = *in
	if in.EnablePeeringRouteSharing != nil {
		in, out := &in.EnablePeeringRouteSharing, &out.EnablePeeringRouteSharing
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrivateEndpoint != nil {
		in, out := &in.EnablePrivateEndpoint, &out.EnablePrivateEndpoint
		*out = new(bool)
		**out = **in
	}
	if in.EnablePrivateNodes != nil {
		in, out := &in.EnablePrivateNodes, &out.EnablePrivateNodes
		*out = new(bool)
		**out = **in
	}
	if in.MasterIpv4CidrBlock != nil {
		in, out := &in.MasterIpv4CidrBlock, &out.MasterIpv4CidrBlock
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateClusterConfigSpec.
func (in *PrivateClusterConfigSpec) DeepCopy() *PrivateClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateClusterConfigStatus) DeepCopyInto(out *PrivateClusterConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateClusterConfigStatus.
func (in *PrivateClusterConfigStatus) DeepCopy() *PrivateClusterConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateClusterConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLimit) DeepCopyInto(out *ResourceLimit) {
	*out = *in
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(int64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(int64)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLimit.
func (in *ResourceLimit) DeepCopy() *ResourceLimit {
	if in == nil {
		return nil
	}
	out := new(ResourceLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUsageExportConfig) DeepCopyInto(out *ResourceUsageExportConfig) {
	*out = *in
	if in.BigqueryDestination != nil {
		in, out := &in.BigqueryDestination, &out.BigqueryDestination
		*out = new(BigQueryDestination)
		**out = **in
	}
	if in.ConsumptionMeteringConfig != nil {
		in, out := &in.ConsumptionMeteringConfig, &out.ConsumptionMeteringConfig
		*out = new(ConsumptionMeteringConfig)
		**out = **in
	}
	if in.EnableNetworkEgressMetering != nil {
		in, out := &in.EnableNetworkEgressMetering, &out.EnableNetworkEgressMetering
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUsageExportConfig.
func (in *ResourceUsageExportConfig) DeepCopy() *ResourceUsageExportConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceUsageExportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxConfigClusterStatus) DeepCopyInto(out *SandboxConfigClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxConfigClusterStatus.
func (in *SandboxConfigClusterStatus) DeepCopy() *SandboxConfigClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxConfigClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShieldedInstanceConfigClusterStatus) DeepCopyInto(out *ShieldedInstanceConfigClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShieldedInstanceConfigClusterStatus.
func (in *ShieldedInstanceConfigClusterStatus) DeepCopy() *ShieldedInstanceConfigClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ShieldedInstanceConfigClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCondition) DeepCopyInto(out *StatusCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCondition.
func (in *StatusCondition) DeepCopy() *StatusCondition {
	if in == nil {
		return nil
	}
	out := new(StatusCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TierSettings) DeepCopyInto(out *TierSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TierSettings.
func (in *TierSettings) DeepCopy() *TierSettings {
	if in == nil {
		return nil
	}
	out := new(TierSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticalPodAutoscaling) DeepCopyInto(out *VerticalPodAutoscaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticalPodAutoscaling.
func (in *VerticalPodAutoscaling) DeepCopy() *VerticalPodAutoscaling {
	if in == nil {
		return nil
	}
	out := new(VerticalPodAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadIdentityConfig) DeepCopyInto(out *WorkloadIdentityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadIdentityConfig.
func (in *WorkloadIdentityConfig) DeepCopy() *WorkloadIdentityConfig {
	if in == nil {
		return nil
	}
	out := new(WorkloadIdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadMetadataConfigClusterStatus) DeepCopyInto(out *WorkloadMetadataConfigClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadMetadataConfigClusterStatus.
func (in *WorkloadMetadataConfigClusterStatus) DeepCopy() *WorkloadMetadataConfigClusterStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadMetadataConfigClusterStatus)
	in.DeepCopyInto(out)
	return out
}
