apiVersion: v1
data:
  password: Y2hhbmdlbWU=
kind: Secret
metadata:
  name: example-sql-user
  namespace: crossplane-system
---
apiVersion: sql.gcp.jet.crossplane.io/v1alpha2
kind: User
metadata:
  name: example-user
spec:
  forProvider:
    passwordSecretRef:
      name: example-sql-user
      namespace: crossplane-system
      key: password
    instanceRef:
      name: example-instance
