apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: example-cloudsql-instance
spec:
  forProvider:
    databaseVersion: POSTGRES_11
    region: us-west2
    settings:
      tier: db-custom-1-3840
      dataDiskSizeGb: 20
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: example-cloudsql-connection-details
    namespace: crossplane-system