---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  name: test-sakey
spec:
  forProvider:
    # Google Cloud API RRN of a ServiceAccount is expected in "serviceAccount" field
    # serviceAccount: projects/crossplane-playground/serviceAccounts/perfect-test-sa@crossplane-playground.iam.gserviceaccount.com
    serviceAccountRef:
      name: perfect-test-sa
    # keyAlgorithm: "KEY_ALG_RSA_2048"
    # privateKeyType: "TYPE_GOOGLE_CREDENTIALS_FILE"
    # publicKeyType: TYPE_RAW_PUBLIC_KEY
  deletionPolicy: Delete
  providerConfigRef:
    name: gcp-provider
  writeConnectionSecretToRef:
    name: test-sakey
    namespace: default
