---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountPolicy
metadata:
  name: crossplane-test-sa-policy
spec:
  forProvider:
    serviceAccountRef:
      name: perfect-test-sa
    policy:
      bindings:
        # Ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
        - role: roles/iam.workloadIdentityUser
          members:
            - serviceAccount:PROJECT_ID.svc.id.goog[K8S_NAMESPACE/KSA_NAME]
  providerConfigRef:
    name: gcp-provider