apiVersion: cloudplatform.gcp.jet.crossplane.io/v1alpha2
kind: ServiceAccountKey
metadata:
  name: example-service-account-key
spec:
  forProvider:
    serviceAccountIdRef:
      name: example-service-account
    publicKeyType: TYPE_X509_PEM_FILE
  writeConnectionSecretToRef:
    name: example-service-account-key-secret
    namespace: crossplane-system
