apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: mysql-instance
spec:
  forProvider:
    databaseVersion: MYSQL_5_7
    region: us-west2
    replicaNames:
      - "mysql-replica"
    settings:
      tier: db-custom-1-3840
      dataDiskSizeGb: 20
      backupConfiguration:
        binaryLogEnabled: true
        enabled: true
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: example-cloudsql-connection-details
    namespace: crossplane-system
